### ISSUE TITLE
Proposal Review: 9/7

### ISSUE THREAD

**Issue by BCrawfordScott** [Liming0824/Instagraph#1]
Schema: 
- [x] Change wiki page from 'instagraph project schema' to just 'schema'.
- [x] Remove 'user_url', or if it is for the user's profile image, change to img_url.
- [x] Combine posts and post image tables.  Since each post will only have on image (for now) the image_url can live on the posts table.  We can always refactor for multiple images per post later.

Sample State: 
- [x]  add 'Ids' to any field of array's that is supposed to hold ids
- [x] refactor to remove post_imgs  and have each post contain it's img_url.
- Shares seems a little bulky in front end state right now.  We will look more into this when we get to that mvp during fullstacks.  

Routes: 
- Add get `api/user/:id`  to  backend for a single user's info. 

Overall great work, let me know if you have more in depth questions.

**Comment by Liming0824** [comment]
Thank you for your comment, I have changed the schema title, and add 'img_url' column on 'posts' table, also made some changes on 'Sample State' and 'backend`, please check
